### PR TITLE
added accepts_marketing_updated_at to customer schema

### PR DESCRIPTION
**Pull request by mingmamma**
I am very interested in contributing to this project! This is my first attempt and I just picked the [current first issue on the list #57](https://github.com/singer-io/tap-shopify/issues/57) to have a go. Any feedbacks and changes are welcome as I am just figuring out how the process works. Cheers!

# Description of change
Added `accepts_marketing_updated_at`

# QA steps
Not applicable. I haven't found out what tests are required. I will go on having a look and add any tests as required.

# Risks
Not applicable. Not trying out first.

# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @mingmamma, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @mingmamma!

Thank you for signing the Singer Contribution License Agreement.

**Comment by saurabh-anatta** [comment]
@cmerrick when is it going to deploy?

**Review by dmosorast — APPROVED** [review]
@mingmamma Thanks for submitting this! As for testing, usually an addition to a schema is safe, but there are a few concerns here, which I have investigated and determined to be okay. But just for future reference.

1. It's always best to run the tap and directly observe the data being added to the schema. `target-stitch` has a `--dry-run` flag that doesn't require config and will validate the schema automatically. [More on running taps and targets](https://github.com/singer-io/getting-started/blob/master/docs/RUNNING_AND_DEVELOPING.md#running-singer-with-python)
2. For schema changes specifically, it's important to confirm that the datatype is correct for the datatype that is actually returned from the API. (Note: This may not always match the API's documentation). Since a `date-time` formatted string is a rather restrictive type, I'm okay with merging this.
3. When fields are added to the schema, it's good to confirm whether or not they need added to the request. This and point 2 above would all be covered by running the tap and confirming that data is returned.

Again, I'm okay with merging this as-is. These points above should be helpful if you hope to contribute more in the future! Cheers 🙌

**Pull request merged**
