### PR TITLE
TDL-6553: Add shop info in record - (Copy of  PR 73)

### PR DESCRIPTION
**Pull request by savan-chovatiya**
# Description of change
TDL-6553: Add shop info to the records
# QA steps
 - [x] automated tests passing
 - [x] manual qa steps passing (list below)
    - Verified that all three fields related to shop information are emitted for every stream if selected in the catalog.
    -  Verified that all three fields related to shop information are skipped if not selected in the catalog
 
# Risks

# Rollback steps
 - revert this branch

### CODE REVIEW

**Review by dbshah1212 — APPROVED** [review]

**Review by karanpanchal-crest — APPROVED** [review]

**Review by KrisPersonal — CHANGES_REQUESTED** [review]
Remove this function add_synthetic_keys_to_schema and hardcode the schema for new SDC fields and make sure that the tests are passing

**Comment by savan-chovatiya** [comment]
> Remove this function add_synthetic_keys_to_schema and hardcode the schema for new SDC fields and make sure that the tests are passing

The function add_synthetic_keys_to_schema() is adding _sdc fields to all the streams schema. If we remove it and add those fields directly in schema JSON files then we have to add those fields in newly added streams as well. eg. In newly added 3 streams as part #114  and #118  And if any new streams are added in the future, the developer needs to add these fields to the new stream schema as well.

**Review by kspeer825 — COMMENTED** [review]
This is a good tap-tester test for this change. But may want to consider adding unittests if you are going to stick with this dynamic approach.

**Review by dmosorast — COMMENTED** [review]
Holding off on approval, since I'm not sure about the big picture around this PR, but I'm okay with the pattern used here.

We like to hard code as much as possible for discoverability/searchability, but the risk of forgetting to add these fields in future streams as the tap is extended is a reasonable point. ✅

**Comment by savan-chovatiya** [comment]
#

> This is a good tap-tester test for this change. But may want to consider adding unittests if you are going to stick with this dynamic approach.

Added unittest for add_synthetic_keys_to_schema() function.

**Review by luandy64 — APPROVED** [review]

**Review by KrisPersonal — APPROVED** [review]

**Pull request merged**
